import React, { Fragment } from 'react';
import { Card } from '../constants/molecules';
import { CardList } from '../constants/organisms';

export default () => (
  <Fragment>
    <CardList
      title="Scholen"
    >
      <Card
        title="Basischool"
        list={[
          'test',
          'test',
          'test',
        ]}
      />
      <Card
        title="Basischool"
        list={[
          'test',
          'test',
          'test',
        ]}
      />
      <Card
        title="Basischool"
        list={[
          'test',
          'test',
          'test',
        ]}
      />
      <Card
        title="Basischool"
        list={[
          'test',
          'test',
          'test',
        ]}
      />
      <Card
        title="Basischool"
        list={[
          'test',
          'test',
          'test',
        ]}
      />
      <Card
        title="Basischool"
        list={[
          'test',
          'test',
          'test',
        ]}
      />
      <Card
        title="Basischool"
        list={[
          'test',
          'test',
          'test',
        ]}
      />
      <Card
        title="Basischool"
        list={[
          'test',
          'test',
          'test',
        ]}
      />
      <Card
        title="Basischool"
        list={[
          'test',
          'test',
          'test',
        ]}
      />
      <Card
        title="Basischool"
        list={[
          'test',
          'test',
          'test',
        ]}
      />
    </CardList>
  </Fragment>
);
